name: Test Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          
      - name: Install dependencies
        run: go mod tidy
        
      - name: Test build
        run: |
          # Test that Sona builds successfully
          echo "Testing build..."
          go build -o build/sona cmd/sona/main.go
          
          # Test that the binary works
          echo "Testing binary..."
          ./build/sona --help
          
          echo "✅ Build test passed!"
